local function clear_blade_nav_modules()
  for k in pairs(package.loaded) do
    if k:match("^blade%-nav") then
      package.loaded[k] = nil
    end
  end
end

describe("core.config", function()
  local config

  before_each(function()
    clear_blade_nav_modules()
    config = require("blade-nav.core.config")
  end)

  describe("setup", function()
    it("merges user options with defaults", function()
      config.setup({ debug = true })
      local cfg = config.get()
      assert.is_true(cfg.debug)
      assert.is_true(cfg.enable)
      assert.equals(50000, cfg.cache_timeout)
    end)

    it("uses defaults when no options provided", function()
      config.setup()
      local cfg = config.get()
      assert.is_false(cfg.debug)
      assert.is_true(cfg.enable)
      assert.equals("./jsconfig.json", cfg.jsconfig_path)
    end)

    it("re-merges when explicit options are passed again", function()
      config.setup({ debug = true })
      config.setup({ debug = false })
      assert.is_false(config.get().debug)
    end)

    it("keeps cached config on a bare re-entrant call (no args)", function()
      config.setup({ debug = true })
      config.setup()
      assert.is_true(config.get().debug)
    end)
  end)

  describe("get", function()
    it("returns full config when no key", function()
      config.setup()
      local cfg = config.get()
      assert.is_table(cfg)
      assert.is_table(cfg.handlers)
    end)

    it("returns specific key value", function()
      config.setup({ cache_timeout = 9999 })
      assert.equals(9999, config.get("cache_timeout"))
    end)

    it("returns nil for unknown key", function()
      config.setup()
      assert.is_nil(config.get("nonexistent_key"))
    end)

    it("does not act as setter", function()
      config.setup()
      local original = config.get("debug")
      config.get("debug")
      assert.equals(original, config.get("debug"))
    end)
  end)

  describe("set", function()
    it("updates a config value", function()
      config.setup()
      config.set("debug", true)
      assert.is_true(config.get("debug"))
    end)
  end)

  describe("handlers defaults", function()
    it("enables all handlers by default", function()
      config.setup()
      local handlers = config.get("handlers")
      assert.is_true(handlers.directive)
      assert.is_true(handlers.view)
      assert.is_true(handlers.route)
      assert.is_true(handlers.config)
      assert.is_true(handlers.component)
      assert.is_true(handlers.livewire)
      assert.is_true(handlers.inertia)
      assert.is_true(handlers.vue)
    end)

    it("allows disabling specific handlers", function()
      config.setup({ handlers = { route = false } })
      local handlers = config.get("handlers")
      assert.is_false(handlers.route)
      assert.is_true(handlers.view)
    end)
  end)

  describe("integrations defaults", function()
    it("enables all integrations by default", function()
      config.setup()
      local integrations = config.get("integrations")
      assert.is_true(integrations.gf)
      assert.is_true(integrations.cmp)
      assert.is_true(integrations.coq)
    end)
  end)
end)

describe("require blade-nav (no circular dependency)", function()
  it("loads without error", function()
    clear_blade_nav_modules()
    local ok, err = pcall(require, "blade-nav")
    assert.is_true(ok, "require('blade-nav') failed: " .. tostring(err))
  end)

  it("exposes setup function", function()
    clear_blade_nav_modules()
    local mod = require("blade-nav")
    assert.is_function(mod.setup)
  end)
end)
